default:
	javac CloseInterval.java Interval.java OpenInterval.java SemiOpenInterval.java Main.java
	java Main
	rm CloseInterval.class Interval.class OpenInterval.class SemiOpenInterval.class Main.class
	